name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
sort-direction: ascending
categories:
  - title: "Breaking changes"
    label: "breaking change"
  - title: "Features"
    labels:
      - "feature"
  - title: "Code enhancements"
    labels:
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Documentation"
    label: "documentation"
  - title: "Dependency Updates"
    labels:
      - "dependencies"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  $CHANGES
